### ISSUE TITLE
mave_nt strings and deletion in/across PAM codon

### ISSUE THREAD

**Issue by delagee** [cancerit/VaLiAnT#8]
When using the deletion mutators (2del1, 2del0, 1del), the mave_nt string does not accurately represent the variant when the deletion impacts a PAM codon but does not encompass the PAM protected nucleotide.

The current description indicates a larger deletion than the actual one, it would be better represented using the delins operator as used for the snv mutator. 
The attached html notebook points to the specific relevant variants and illustrates the expected behaviour. 

Also attached are the files required to reproduce this issue. 

Version used : main, tag 3.0.0

[valiant_mave_nt_del.zip](https://github.com/cancerit/VaLiAnT/files/11888001/valiant_mave_nt_del.zip)

**Comment by lbarbon** [comment]
Resolved in version 3.0.1.
